
#Install useful packages from CRAN

install.packages("tidyverse")
install.packages("kableExtra")
install.packages("janitor")
install.packages("mlogit")
install.packages("googleVis")
install.packages("AER")
install.packages("estimatr")
install.packages("broom")
install.packages("lubridate")
install.packages("R.utils")
install.packages("readr")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("dplyr")
install.packages("tidyr")
install.packages("randtoolbox")
install.packages("devtools")
install.packages("stringr")
install.packages('installr')
install.packages("caret")
install.packages("skimr")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("ranger")
install.packages("glmnet")
install.packages("BLPestimatoR")
install.packages("DiagrammeR")
install.packages("stargazer")
install.packages("evd")
install.packages("maxLik")
install.packages("recipes")
install.packages("forcats")
install.packages("grf")
install.packages("hdm")
install.packages("matrixStats")
install.packages("evd")
install.packages("maxLik")

# Use Prof Sebastian Kranz's repository to install RTutor and other packages
options(repos=unique(c(getOption("repos"),"https://skranz-repo.github.io/drat/")))
install.packages("RTutor",repos=unique(c(getOption("repos"),"https://skranz-repo.github.io/drat/")))
install.packages("mlogitExtras",repos=unique(c(getOption("repos"),"https://skranz-repo.github.io/drat/")))
install.packages("sktools", repos=unique(c(getOption("repos"),"https://skranz-repo.github.io/drat/")))

